title: Ascend - The Self-Improvement App for Community Challenges & Goal Tracking
apkallu_title: Apkallu
ascend_title: Ascend
email: help@apkallu.co.uk
description: >-
  Join Ascend, the social platform for self-improvement.
  Take part in community challenges, track goals, and celebrate achievements.
  Coming soon to Android & iOS!

keywords: self-improvement, community challenges, goal tracking app, personal growth, Ascend app, best self-improvement app, personal goals, self-improvement platform

baseurl: ""
url: "https://apkallu.co.uk"

plugins:
  - jekyll-sitemap
  - jekyll-feed

social:
  facebook: https://www.facebook.com/ascend.app.fb/
  instagram: https://www.instagram.com/ascend.app.ig
  tiktok: https://www.tiktok.com/@ascendapp
  youtube: https://www.youtube.com/@ascend-app
  medium: https://medium.com/feed/ascend-app
  linktree: https://linktr.ee/ascendapp

app:
  testing_form: https://docs.google.com/forms/d/e/1FAIpQLSfK4L5aW8uSz3lSrodQCsPTwNDf54fA-UVXA4W6_3NPdRFnqQ/viewform

defaults:
  - scope:
      path: ""
    values:
      layout: "default"

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - .gitignorec